info:
  title: test
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
swagger: '2.0'
securityDefinitions:
  keystone:
    description: OpenStack Keystone Authentication
    type: apiKey
    in: header
    name: x-auth-token

security: []

paths:
  /api/v1/clusters/:
    get:
      operationId: ListClusters
      summary: List available clusters
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Cluster'
      security:
        - keystone: []
    post:
      operationId: CreateCluster
      summary: Create a cluster
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Cluster'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Cluster'
      security:
        - keystone: []

definitions:
  Cluster:
    type: object
    properties:
      name:
        description: name of the cluster
        type: string