info:
  title: Crypto Exchange Rates
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
swagger: '2.0'
securityDefinitions:
  keystone:
    description: OpenStack Keystone Authentication
    type: apiKey
    in: header
    name: x-auth-token

security: []

paths:
  /api/v1/cryptoData/:
    get:
      operationId: ListCryptoCurrencies
      summary: List available CryptoCurrencies
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/CryptoCurrency'
      security:
        - keystone: []

definitions:
  CryptoCurrency:
    type: object
    properties:
      name:
        description: name of the CryptoCurrency
        type: string
      symbol:
        description: symbol of the CryptoCurrency
        type: string
      usd:
        description: price, market_cap, percent_change of the CryptoCurrency(USD)
        type: object
      last_updated:
        description: Last updated datetime(UNIX timestamp)
        type: string
